// Each new term in the Fibonacci sequence 
// is generated by adding the previous two 
// terms. By starting with 1 and 2, the first 
// 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci 
// sequence whose values do not exceed four 
// million, find the sum of the even-valued 
// terms.

var fibs = [1, 2];
var evenFibs = [];
var sum = 0;

var fibFinder = function() {
  for(let i = 1; fibs[i] < 4000000; i++) {
    var temp = fibs[i] + fibs[i - 1];
    fibs.push(temp);
  };
}

var addEvens = function(array) {
  for(let i = 0; i < array.length; i++) {
    if (array[i] % 2 === 0) {
       sum += array[i];
      evenFibs.push(array[i])
    };
  };
  console.log(sum)
}

fibFinder();
addEvens(fibs);